# Generated by Django 5.1.5 on 2025-01-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenia_usu',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_usu',
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(default='default_google_id', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
