# Generated by Django 5.1.5 on 2025-01-27 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0002_remove_usuario_contrasenia_usu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_id_con',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendSenias.configuracion'),
        ),
    ]
