# Generated by Django 5.1.5 on 2025-01-27 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0003_alter_usuario_fk_id_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_id_con',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendSenias.configuracion'),
        ),
    ]
