# Generated by Django 5.1.5 on 2025-01-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0005_categoria_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_file', models.FileField(blank=True, null=True, upload_to='metadata/')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('weights_file', models.FileField(blank=True, null=True, upload_to='weights/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.AddField(
            model_name='traduccion',
            name='fk_id_modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendSenias.modelo'),
        ),
    ]
