# Generated by Django 5.1.5 on 2025-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0006_modelo_traduccion_fk_id_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AddField(
            model_name='modelo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(default='modelos', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='metadata_file',
            field=models.FileField(default='default_metadata_file.json', upload_to='modelos'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='model_file',
            field=models.FileField(default='model_file.json', upload_to='modelos'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='weights_file',
            field=models.FileField(default='weights_file.bin', upload_to='modelos'),
        ),
        migrations.AlterModelTable(
            name='modelo',
            table=None,
        ),
    ]
