# Generated by Django 5.1.5 on 2025-01-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0007_alter_modelo_options_modelo_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='activo',
        ),
    ]
