# Generated by Django 5.1.5 on 2025-02-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0008_remove_modelo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=255)),
                ('descripcion_jue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_nivel', models.CharField(max_length=50)),
                ('descripcion_nivel', models.TextField()),
                ('FK_id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='backendSenias.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('resultado', models.IntegerField()),
                ('FK_id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendSenias.juego')),
                ('FK_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendSenias.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField()),
                ('fecha_ob_puntaje', models.DateTimeField()),
                ('FK_id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendSenias.nivel')),
                ('FK_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendSenias.usuario')),
            ],
        ),
    ]
