# Generated by Django 5.1.5 on 2025-02-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0009_juego_nivel_partida_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha_fin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='fecha_ob_puntaje',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
