# Generated by Django 5.1.5 on 2025-02-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendSenias', '0010_alter_partida_fecha_fin_alter_partida_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='FK_id_nivel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendSenias.nivel'),
        ),
    ]
